// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamStackedCards from "@/components/sections/team/TeamStackedCards";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
              <TeamStackedCards
                textAnimation="fade-blur"
                tag="Team"
                title="The CEO"
                description="The creative mind behind your next project."
                members={[
                  {
                    name: "Ciara Collins",
                    role: "CEO",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JNY2WoF3o8mxqLzes9ovx1K1AY/uploaded-1789571828855-djwnjqkg.jpg",
                  },
                  {
                    name: "",
                    role: "",
                    imageSrc: "https://webuild-dev.s3.eu-north-1.amazonaws.com/default/templates/web-agency-2/team-2.webp",
                  },
                  {
                    name: "",
                    role: "",
                    imageSrc: "https://webuild-dev.s3.eu-north-1.amazonaws.com/default/templates/web-agency-2/team-3.webp",
                  },
                ]}
              />
            </div>
  );
}
