// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamStackedCards from "@/components/sections/team/TeamStackedCards";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
              <TeamStackedCards
                textAnimation="fade-blur"
                tag="Team"
                title="The CEO"
                description="The creative mind behind your next project."
                members={[
                  {
                    name: "Ciara Collins",
                    role: "CEO",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JNY2WoF3o8mxqLzes9ovx1K1AY/uploaded-1789571828855-djwnjqkg.jpg",
                  },
                  {
                    name: "",
                    role: "",
                    imageSrc: "https://images.pexels.com/photos/34860711/pexels-photo-34860711.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=34860711",
                  },
                  {
                    name: "",
                    role: "",
                    imageSrc: "https://images.pexels.com/photos/4814074/pexels-photo-4814074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=4814074",
                  },
                ]}
              />
            </div>
  );
}
