/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

const members = [
  {
    name: "Ciara Collins",
    role: "Founder & CEO",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3JNY2WoF3o8mxqLzes9ovx1K1AY/uploaded-1789571828855-djwnjqkg.jpg"
  }
];

type TeamMember = {
  name: string;
  role: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const TeamInline = () => (
  <section aria-label="Team section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10 w-content-width mx-auto">
      <div className="flex flex-col items-center gap-2">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Team"}</p>
        </div>

        <TextAnimation
          text={"The CEO"}
          variant={"fade-blur"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"The creative mind behind your next project."}
          variant={"fade-blur"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(undefined || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <ScrollReveal variant="slide-up" className="flex flex-wrap justify-center gap-y-4 xl:gap-y-5 2xl:gap-y-6">
        {members.map((member) => (
          <div key={member.name} className="flex flex-col items-center w-[55%] md:w-[28%] -mx-[4%] md:-mx-[2%] text-center">
            <div className="p-2 xl:p-3 2xl:p-4 mb-4 xl:mb-5 2xl:mb-6 w-full aspect-square card rounded-full overflow-hidden">
              <ImageOrVideo imageSrc={member.imageSrc} videoSrc={member.videoSrc} className="rounded-full!" />
            </div>
            <span className="w-4/5 text-2xl font-semibold leading-snug truncate">{member.name}</span>
            <span className="w-4/5 text-base leading-snug opacity-75 truncate">{member.role}</span>
          </div>
        ))}
      </ScrollReveal>
    </div>
  </section>
);

export default function TeamSection() {
  return (
    <div data-webild-section="team" data-section="team" id="team">
      <TeamInline />
    </div>
  );
}
